### ISSUE TITLE
How to iterate the ROOMS(CHashMap)?

### ISSUE THREAD

**Issue by rts-gordon** [thruster-rs/thruster-socketio#18]
Hi @trezm 
  I use into_iter() to iterate the ROOMS, but there are errors:

```
 for (key, value) in ROOMS.into_iter()

errors:
 move occurs because value has type `CHashMap<std::string::String, Vec<ChannelPair>>`, which does not implement the `Copy` trait
```

  So how to iterate the ROOMS?
  And why the thruster-socketio must use CHashMap, could it be changed to HashMap?
  If it can be changed to HashMap, I think in function rooms::join_channel_to_room, we don't use the remove function first.

**Comment by trezm** [comment]
We need to use CHashMap because it's shared across threads, so it needs to be a structure with concurrency.

Is there a reason you need to own the iterator? Can you just use `.iter()` and use the borrows instead?

**Comment by rts-gordon** [comment]
I want to print all socket_id in every ROOMS, so need iterate ROOMS.  But it seems there is no way to iterate.

**Comment by trezm** [comment]
Hmm, I see, yes, it's an interesting question. If you try changing the `CHashMap` to a normal `HashMap` you'll see the issue -- because it needs to be borrowed as mutable and accessed from multiple threads, there's a concurrency issue that a normal `HashMap` isn't equipped to solve.

I don't think it makes sense to swap out the `CHashMap` for another data structure, because the perf is very good for it. That being said, perhaps you can keep a second data structure, maybe a `Vec` behind a `Mutex`, that could keep a list of socket ids separately. It's a bit more memory, but will limit the locking access to the variable to only when you need it rather than whenever the `ROOMS` variable needs to be changed.
